baseURL = "https://brzuchal.com/"
languageCode = "en-us"
title = "brzuchal"
theme = "minimal"
#subtitle = ""
description	= "Personal Blog"
timezone = "Europe/Warsaw"
url	= "https://brzuchal.com/"
permalink = ":year/:month/:title"
footnoteReturnLinkContents = "^"
showcomments = true
disqusShortname = "brzuchal"
googleAnalytics = "UA-3332455-25"
enableGitInfo = true
enableRobotsTXT = true

[author]
    name = "Michał Brzuchalski"
    email = "brzuchal@php.net"

[params]
    author = "Michał Brzuchalski"
    profilePic = "https://www.gravatar.com/avatar/2e1f274414ce20810607c305f035c239?s=240&d=mp"
    description = "Personal blog"
    githubUsername = "brzuchal"
    accent = "#ffa412"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    # highlightStyle = "solarized-dark"
    highlightStyle = "github-gist"
    highlightLanguages = ["php", "go", "haskell", "kotlin", "scala", "swift"]

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[menu]
  [[menu.main]]
  identifier = "index"
  name = "Home"
  pre = "<i class='fa fa-home'></i>"
  url = "/"
  weight = -1000

  [[menu.main]]
  identifier = "about"
  name = "About me"
  pre = "<i class='fa fa-address-card'></i>"
  url = "/about/"
  weight = -10

  [[menu.main]]
  name = "Posts"
  post = "<span class='alert'>Posts</span>"
#  pre = "<i class='fa fa-book'></i>"
  url = "/posts/"
  weight = -100

[[menu.icon]]
    url = "mailto:brzuchal@php.net"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/brzuchal"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/mbrzuchalski"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/brzuchalski/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/users/1238574/brzuchal"
    name = "stack-overflow"
    weight = 5

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
